package pojo;
// Generated 12.May.2018 09:01:46 by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kisi generated by hbm2java
 */
@Entity
@Table(name = "kisi")
public class Kisi implements java.io.Serializable {

	private Integer kid;
	private String kname;
	private String ksurname;
	private String kmail;
	private String kpassword;

	public Kisi() {
	}

	public Kisi(String kname, String ksurname, String kmail, String kpassword) {
		this.kname = kname;
		this.ksurname = ksurname;
		this.kmail = kmail;
		this.kpassword = kpassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "kid", unique = true, nullable = false)
	public Integer getKid() {
		return this.kid;
	}

	public void setKid(Integer kid) {
		this.kid = kid;
	}

	@Column(name = "kname", nullable = false)
	public String getKname() {
		return this.kname;
	}

	public void setKname(String kname) {
		this.kname = kname;
	}

	@Column(name = "ksurname", nullable = false)
	public String getKsurname() {
		return this.ksurname;
	}

	public void setKsurname(String ksurname) {
		this.ksurname = ksurname;
	}

	@Column(name = "kmail", nullable = false)
	public String getKmail() {
		return this.kmail;
	}

	public void setKmail(String kmail) {
		this.kmail = kmail;
	}

	@Column(name = "kpassword", nullable = false, length = 32)
	public String getKpassword() {
		return this.kpassword;
	}

	public void setKpassword(String kpassword) {
		this.kpassword = kpassword;
	}

}
